export const ADD_SHIFT = 'ADD_SHIFT'

export const GET_SELECTED_DATE = 'GET_SELECTED_DATE'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'

export const GET_ALL_POSITIONS = 'GET_ALL_POSITIONS'

export const GET_COMMETNS_FOR_SELECTED_DATE = 'GET_COMMENTS_FOR_SELECTED_DATE'

export const GET_SCHEDULES = 'GET_SCHEDULES'

export const GET_LOCATIONS = 'GET_LOCATIONS'

export const GET_ALL_VACANCIES= 'GET_ALL_VACANCIES'

export const ADD_NEW_VACANCY= 'ADD_NEW_VACANCY'

export const GET_TASK_STATUSES = 'GET_TASK_STATUSES'

export const GET_TASKS = 'GET_TASKS'

export const GET_FREQUENCIES = 'GET_FREQUENCIES'

export const GET_ALL_USERS = 'GET_ALL_USERS'
