export const ADD_SHIFT = 'ADD_SHIFT'

export const GET_SELECTED_DATE = 'GET_SELECTED_DATE'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'

export const GET_ALL_POSITIONS = 'GET_ALL_POSITIONS'

export const GET_COMMETNS_FOR_SELECTED_DATE = 'GET_COMMENTS_FOR_SELECTED_DATE'

export const GET_SCHEDULES = 'GET_SCHEDULES'

export const GET_LOCATIONS = 'GET_LOCATIONS'
